CREATE TABLE [dbo].[FileVersion] (
    [Id]        UNIQUEIDENTIFIER DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [FileId]    UNIQUEIDENTIFIER NOT NULL,
    [Fileize]   BIGINT           NOT NULL,
    [DeltaSize] BIGINT           NOT NULL,
    [FileHash]  BINARY (16)      NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
);

