CREATE TABLE [dbo].[File] (
    [Id]          UNIQUEIDENTIFIER DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [DirectoryId] UNIQUEIDENTIFIER NOT NULL,
    [FileName]    NVARCHAR (255)   NOT NULL,
    [IsLocked]    BIT              NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
);

